"""'users_table'

Revision ID: 0fbdf394dffe
Revises: 
Create Date: 2018-11-26 10:56:07.765303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fbdf394dffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_table('item')
    op.drop_table('herolist (1)')
    op.drop_table('summoner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summoner',
    sa.Column('summoner_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('summoner_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('summoner_rank', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('summoner_description', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('herolist (1)',
    sa.Column('ename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('new_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hero_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('skin_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hero_type2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pay_type', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('item',
    sa.Column('item_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('item_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('item_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('total_price', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('des1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('des2', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
