"""'users_table'

Revision ID: 22d3587fdc13
Revises: ff96774e0a7a
Create Date: 2018-11-26 11:19:41.524978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d3587fdc13'
down_revision = 'ff96774e0a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_item_des1'), 'item', ['des1'], unique=True)
    op.create_index(op.f('ix_item_des2'), 'item', ['des2'], unique=True)
    op.create_index(op.f('ix_item_item_name'), 'item', ['item_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_item_name'), table_name='item')
    op.drop_index(op.f('ix_item_des2'), table_name='item')
    op.drop_index(op.f('ix_item_des1'), table_name='item')
    # ### end Alembic commands ###
